"""Shared text, answer-extraction, and reproducibility helpers.

The ACC algorithm path uses `extract_code_block` to clean model-generated Python before execution and
`set_all_seeds` to make train/eval runs reproducible. Existing math-answer extraction remains here
because the repository still supports the original math evaluation path."""

import re, logging

from transformers import set_seed
import torch

logger = logging.getLogger(__name__)


def strip_thinking_channels(text: str) -> str:
    if not text:
        return ""
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    text = re.sub(r"<\|channel>thought\n.*?<channel\|>", "", text, flags=re.DOTALL)
    return text.strip()


def extract_code_block(text: str) -> str:
    """
    Robustly extract code from model output, handling markdown,
    custom tags ([BEGIN], <code>), and common suffixes.
    """
    if not text:
        return ""

    code = strip_thinking_channels(text)
    if "[BEGIN]" in code and "[DONE]" in code:
        code = code.split("[BEGIN]")[1].split("[DONE]")[0]

    if "```python" in code:
        code = code.split("```python")[1].split("```")[0]
    elif "```" in code:
        parts = code.split("```")
        if len(parts) >= 3:
            code = parts[1]
        elif len(parts) == 2:
            p0, p1 = parts[0].strip(), parts[1].strip()
            if p0 and not p1:
                code = p0
            elif p1 and not p0:
                code = p1
            else:
                code = parts[0] if len(parts[0]) > len(parts[1]) else parts[1]

    if "<code>" in code:
        code = code.split("<code>")[-1]
    if "</code>" in code:
        code = code.split("</code>")[0]

    return code.strip()



def check_stop_condition(feedback: str) -> bool:
    feedback_lower = feedback.lower()

    score_match = re.search(r"(?:Score|Grade|Rating):\s*(\d+)", feedback, re.IGNORECASE)
    if score_match:
        try:
            score = int(score_match.group(1))
            if score <= 10:
                return score >= 9
            if score <= 100:
                return score >= 90
        except ValueError:
            pass

    strong_signals = [
        "perfect",
        "no issues",
        "no bugs",
        "excellent",
        "flawless",
        "no errors",
        "completely correct",
        "works correctly",
    ]

    if "incorrect" in feedback_lower or "not correct" in feedback_lower or "bug" in feedback_lower:
        return False

    matched = sum(1 for sig in strong_signals if sig in feedback_lower)
    return matched >= 2



def extract_math_answer(text: str) -> str:
    """Extract the final answer from a model response.

    Priority order:
    1. The last `Final Answer: ...` line.
    2. The last `\boxed{...}` expression, including nested braces.
    3. The full stripped response as a fallback.

    Args:
        text: Full response generated by the model.

    Returns:
        Extracted answer string.
    """
    # 1) "Final Answer: X"
    fa_matches = re.findall(r"Final Answer:\s*(.+?)(?:\n|$)", text, re.IGNORECASE)
    if fa_matches:
        return fa_matches[-1].strip()

    # 2) \boxed{} with nested-brace support, e.g. \boxed{\frac{1}{2}}.
    boxed: list[str] = []
    i = 0
    while i < len(text):
        idx = text.find(r"\boxed{", i)
        if idx == -1:
            break
        start = idx + len(r"\boxed{")
        depth, j = 1, start
        while j < len(text) and depth > 0:
            if text[j] == "{":
                depth += 1
            elif text[j] == "}":
                depth -= 1
            j += 1
        if depth == 0:
            boxed.append(text[start : j - 1])
        i = idx + 1
    if boxed:
        return boxed[-1].strip()

    # 3) raw text
    return text.strip()



def set_all_seeds(seed: int):
    """Fix random seeds for HuggingFace, CPU torch, and CUDA torch.

    Also enables deterministic cuDNN behavior when CUDA is available. This improves run-to-run
    reproducibility for ACC algorithm SFT/evaluation, at the cost of disabling cuDNN benchmarking.

    Args:
        seed: Seed value to apply across supported libraries.
    """
    set_seed(seed)                        # HuggingFace default seed.
    torch.manual_seed(seed)               # PyTorch CPU seed.
    torch.cuda.manual_seed_all(seed)      # All visible CUDA device seeds.
    if torch.cuda.is_available():
        torch.backends.cudnn.deterministic = True  # Prefer deterministic CUDA kernels.
        torch.backends.cudnn.benchmark = False     # Disable auto-tuned kernel selection.
    logger.info(f"All seeds fixed: {seed} (CPU + CUDA deterministic)")

